# Generated by Django 5.1.7 on 2026-01-20 20:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_currency_account_is_active_account_mask_and_more'),
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('low_balance', 'Low Balance'), ('unusual_spending', 'Unusual Spending'), ('budget_exceeded', 'Budget Exceeded'), ('bill_due', 'Bill Due'), ('large_transaction', 'Large Transaction')], max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='threshold_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
