# Generated by Django 5.0.6 on 2025-02-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.CharField(
                choices=[
                    ("groceries", "Groceries"),
                    ("utilities", "Utilities"),
                    ("entertainment", "Entertainment"),
                    ("transportation", "Transportation"),
                    ("savings", "Savings"),
                    ("miscellaneous", "Miscellaneous"),
                    ("insurance", "Insurance"),
                    ("health", "Health"),
                    ("housing", "Housing"),
                    ("shopping", "Shopping"),
                    ("business", "Business"),
                    ("dining", "Dining"),
                ],
                max_length=50,
            ),
        ),
    ]
