# Generated by Django 6.0.6 on 2026-06-19 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KrakenLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_id', models.CharField(max_length=255, unique=True)),
                ('ref_id', models.CharField(blank=True, default='', max_length=255)),
                ('entry_type', models.CharField(blank=True, default='', max_length=64)),
                ('subtype', models.CharField(blank=True, default='', max_length=64)),
                ('asset', models.CharField(blank=True, default='', max_length=32)),
                ('amount', models.DecimalField(decimal_places=10, default=0, max_digits=24)),
                ('fee', models.DecimalField(decimal_places=10, default=0, max_digits=24)),
                ('balance', models.DecimalField(decimal_places=10, default=0, max_digits=24)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kraken_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-created_at'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='investments_user_id_68ec19_idx'), models.Index(fields=['asset', '-timestamp'], name='investments_asset_25ed8a_idx'), models.Index(fields=['entry_type', '-timestamp'], name='investments_entry_t_62e7b6_idx')],
            },
        ),
    ]
