# Generated by Django 5.1.7 on 2026-01-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='openai_batch_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
