# Generated by Django 5.1.7 on 2026-01-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plaid_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plaidconnection",
            name="institution_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="plaidconnection",
            name="institution_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
