# Generated by Django 5.1.7 on 2026-01-16 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("transactions", "0006_transaction_plaid_transaction_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.CharField(blank=True, max_length=512, null=True)),
                ("ocr_text", models.TextField(blank=True, null=True)),
                (
                    "merchant_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total_amount", models.IntegerField(blank=True, null=True)),
                ("receipt_date", models.DateField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("parsed_data", models.JSONField(blank=True, null=True)),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "processing_status",
                    models.IntegerField(
                        choices=[
                            (0, "pending"),
                            (1, "processing"),
                            (2, "completed"),
                            (3, "failed"),
                        ],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipt",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("clean_name", models.CharField(blank=True, max_length=255, null=True)),
                ("price", models.IntegerField()),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("unit_price", models.IntegerField(blank=True, null=True)),
                (
                    "category_suggestion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="receipts.receipt",
                    ),
                ),
            ],
        ),
    ]
