# Generated by Django 6.0.6 on 2026-06-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('asset_type', models.CharField(blank=True, default='etf', max_length=64)),
                ('provider', models.CharField(blank=True, default='yfinance', max_length=64)),
                ('target_weight_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('active', models.BooleanField(default=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='MarketDailyBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('provider', models.CharField(blank=True, default='yfinance', max_length=64)),
                ('open', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol', '-date'],
                'indexes': [models.Index(fields=['symbol', '-date'], name='market_data_symbol_72aaa1_idx'), models.Index(fields=['provider', 'symbol'], name='market_data_provide_4422f5_idx')],
                'unique_together': {('symbol', 'date', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='MarketMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('as_of', models.DateField()),
                ('provider', models.CharField(blank=True, default='yfinance', max_length=64)),
                ('latest_close', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('return_1d_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('return_5d_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('return_1m_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('volatility_20d_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('moving_average_20d', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('moving_average_50d', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('rsi_14', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol', '-as_of'],
                'indexes': [models.Index(fields=['symbol', '-as_of'], name='market_data_symbol_ac17e4_idx'), models.Index(fields=['provider', 'symbol'], name='market_data_provide_63246d_idx')],
                'unique_together': {('symbol', 'as_of', 'provider')},
            },
        ),
    ]
