# Generated by Django 6.0.6 on 2026-06-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketNewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('provider', models.CharField(blank=True, default='yfinance', max_length=64)),
                ('title', models.CharField(max_length=500)),
                ('publisher', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('summary', models.TextField(blank=True, default='')),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol', '-published_at', '-updated_at'],
                'indexes': [models.Index(fields=['symbol', '-published_at'], name='market_data_symbol_0f1687_idx'), models.Index(fields=['provider', 'symbol'], name='market_data_provide_5c90c3_idx')],
                'unique_together': {('symbol', 'url', 'provider')},
            },
        ),
    ]
