# Generated by Django 5.0.6 on 2025-01-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
