# Generated by Django 5.1.7 on 2026-01-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_alter_transaction_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="description",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_type",
        ),
        migrations.AddField(
            model_name="transaction",
            name="date",
            field=models.DateField(default="2024-01-01"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="name",
            field=models.CharField(default="Transaction", max_length=255),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_channel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
