# Generated by Django 5.1.7 on 2026-01-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0005_rename_timestamp_transaction_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="plaid_transaction_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
