# Generated by Django 5.1.7 on 2026-01-20 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('transactions', '0008_tag_transaction_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_value', models.CharField(max_length=255)),
                ('match_type', models.CharField(choices=[('contains', 'Contains'), ('equals', 'Equals'), ('starts_with', 'Starts With'), ('regex', 'Regex')], default='contains', max_length=20)),
                ('category_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorization_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
