# Generated by Django 5.1.7 on 2026-01-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_transaction_is_transfer_transaction_transfer_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='detected_by_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('discontinued', 'Discontinued')], default='active', max_length=20),
        ),
    ]
